name: Create Windows release
on:
    push:
      tags:
        - 'v*'

jobs:
  create-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageReleaseMsi with Gradle Wrapper
      run: ./gradlew packageReleaseMsi
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./build/compose/binaries/main-release/msi/*.msi
        name: clip4moni.msi
        
  create-windows-release:
    runs-on: windows-latest
    needs: [ create-windows-installer]
    steps:
    - name: Download msi
      uses: actions/download-artifact@v3
      with:
        name: clip4moni.msi
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/Users/runner/work/clip4moni/clip4moni/*.msi"
