name: Create Windows release
on:
    push:
      tags:
        - 'v*'

jobs:
  create-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run packageReleaseMsi with Gradle Wrapper
      run: ./gradlew packageReleaseMsi
    - run: Compress-Archive -Path ./build/compose/binaries/main-release/msi/*.msi -Destination ./clip4moni_windows.zip
    - name: Upload asset
      uses: actions/upload-artifact@v3
      with:
        path: ./clip4moni_windows.zip
        name: clip4moni_windows.zip
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./clip4moni_windows.zip"
